services:
  dev:
    image: node:alpine
    restart: always
    working_dir: /app
    network_mode: host
    volumes:
      - .:/app
    command: sh -c "npm install && npm run dev"
    profiles:
      - dev

  prod:
    build: .
    ports:
      - "80:80"
    profiles:
      - prod